### ISSUE TITLE
Error on restore

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#10]
Hi,
I have upgraded dotnet to version 1.0.1. When I do `dotnet restore` I get the following error:

```sh
/opt/dotnet/sdk/1.0.1/NuGet.targets(97,5): warning : Unable to find a project to restore! [/home/samim/src/KTOP/KTOP.sln]
```

Thanks

**Comment by psamim** [comment]
By the way I am on Archlinux.

**Comment by al1b** [comment]
Thanks @psamim, I know what the problem is I will fix it soon.

**Comment by al1b** [comment]
@psamim Could you please update the source and try to rebuild the project again?

**Comment by psamim** [comment]
Thanks! The error is resolved, but when I want to run the app I get the following error now:
```
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.1
  - Alternatively, install the framework version '1.0.4'.
```

I do the following to run the app:

``` sh
dotnet restore
cd KTOP.CLI
dotnet publish
dotnet ./bin/Debug/netcoreapp1.0/KTOP.CLI.dll
```
Should I downgrade my dotnet (which I can't) or is there other solution like not being dependant on a minor dotnet version?
The weird thing is that when I run `dotnet --version` I get 1.0.1.

Thanks

**Comment by al1b** [comment]
Unfortunately I couldn't re-produce your situation. But it seems it's related to `.NetCore.App` version. I upgraded all projects to `.NetCore.App` version 1.1.

Hope it fix the problem, if it won't we will figure it out.

**Comment by psamim** [comment]
I see that in [KTOP.CLI.csproj](https://github.com/al1b/KTOP/blob/master/src/KTOP.CLI/KTOP.CLI.csproj#L9) we have this line:

```xml
 <RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>
```
Can't we instead have something like `1.*` here? To not depend on minor dotnet version?

**Comment by al1b** [comment]
Could you please try this:

```
dotnet publish -c Release /p:RuntimeFrameworkVersion=1.1.0
```

If it wokrs, I'll change the `.Net` time version in the projects.

**Comment by psamim** [comment]
No, I have the same error:

```
$ dotnet ./bin/Release/netcoreapp1.1/KTOP.CLI.dll

The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.1
  - Alternatively, install the framework version '1.0.4'.
```

**Comment by psamim** [comment]
If I change all `1.0.4` to `1.1.1` in all csproj files, it is resolved.
But there must be a better solution to this.

**Comment by psamim** [comment]
Even changing it to `1.*` resolves the issue, but as I am no expert in dotnet I am not sure if this is a good solution.

**Comment by al1b** [comment]
Thanks @psamim. It'll do the work. Since then we have a CI server to check every commit if they are successful or not.
