### ISSUE TITLE
core dumped error

### ISSUE THREAD

**Issue by behroozramezani** [al1b/KTOP#12]
In ubuntu 16.04 when run this command 
```
./KTOP.CLI "/home/behrooz/Downloads/3102-fa-banoye-nemone-eslam-hazrat-zahra-a.epub" --persian
```
I got this error
```
KTOP - Kindle Text Optimization for Persian eBooks By Ali Bahraminezhad
https://github.com/al1b/KTOP

Begin optimizing the book, this might takes minutes, please wait ...
113 files to process.
processing ...
processing ...
processing ...
processing ...
Segmentation fault (core dumped)
```

**Comment by al1b** [comment]
Could you please attach the e-book file?

**Comment by behroozramezani** [comment]
[banoye-nemone-eslam-hazrat-zahra-a.epub.zip](https://github.com/al1b/KTOP/files/1035784/banoye-nemone-eslam-hazrat-zahra-a.epub.zip)
I have a question about this article. please check comment.
```
http://antipattern.ir/embed-custom-font-in-epub-and-justify-the-book.html
```

**Comment by al1b** [comment]
The project is deprecated please take a look on the new Calibre plugin KiPEO here:
https://github.com/al1b/Calibre-KiPEO

**Comment by al1b** [comment]
@behroozramezani
