### ISSUE TITLE
Persian switch does not work

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#2]
Hi,
I am able to convert my epub file using KTOP successfully. But when using the --persian switch, the following error occurs:

```txt
KTOP - Kindle Text Optimization for Persian eBooks By Ali Bahraminezhad
https://github.com/al1b/KTOP

Begin optimizing the book, this might takes minutes, please wait ...
Error, unfortunatelly something went wrong. You can check log file next to your epub file
Value cannot be null.
Parameter name: serviceType
```

Contents of `--persianerrors.txt`:
```txt
Value cannot be null.
Parameter name: serviceType
   at Autofac.Core.TypedService..ctor(Type serviceType)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at KTOP.Base.BookEngine.ProcessBook(String bookPath) in /home/samim/src/KTOP/src/KTOP.Base/BookEngine.cs:line 98
   at KTOP.CLI.Program.Main(String[] args) in /home/samim/src/KTOP/src/KTOP.CLI/Program.cs:line 43
```

**Comment by psamim** [comment]
I think It is related, I cannot convert `azw3` file.

```txt
Begin optimizing the book, this might takes minutes, please wait ...
Error, unfortunatelly something went wrong. You can check log file next to your epub file
Value cannot be null.
Parameter name: serviceType
```

```txt
Value cannot be null.
Parameter name: serviceType
   at Autofac.Core.TypedService..ctor(Type serviceType)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at KTOP.Base.BookEngine.ProcessBook(String bookPath) in /home/samim/src/KTOP/src/KTOP.Base/BookEngine.cs:line 98
   at KTOP.CLI.Program.Main(String[] args) in /home/samim/src/KTOP/src/KTOP.CLI/Program.cs:line 43
```

**Comment by psamim** [comment]
I found the problem. In https://github.com/al1b/KTOP/blob/master/src/KTOP.CLI/Program.cs#L43 the file is retrieved from the first argument. So the switches (e.g. `--persian`) should not be the first argument passed to KTOP.

**Comment by psamim** [comment]
Maybe argument parsers can be used such as http://www.ndesk.org/Options or http://commandline.codeplex.com/

**Comment by al1b** [comment]
@psamim 

> Maybe argument parsers can be used such as http://www.ndesk.org/Options or http://commandline.codeplex.com/

To be honest, the command line interface that I wrote is something I don't really like! I didn't have had enough time to look for a library like what you introduced, but I think I should look after it.


> I think It is related, I cannot convert azw3 file.
Wow, it should give a better error! since KTOP doesn't support azw3 and mobi yet!


> I found the problem. In https://github.com/al1b/KTOP/blob/master/src/KTOP.CLI/Program.cs#L43 the file is retrieved from the first argument. So the switches (e.g. --persian) should not be the first argument passed to KTOP.

Thanks, I'll take a look.

**Comment by al1b** [comment]
I will use (Microsoft.Extensions.CommandLineUtils)[https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils] to parse command line arguments.

**Comment by al1b** [comment]
@psamim 

Fixed.

**Comment by psamim** [comment]
Thanks! Keep up the good work. :)
