### ISSUE TITLE
EPUB file is executable

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#3]
Hi,

The output epub file in Linux has executable permission which is dangerous and unnecessary. 

Thanks,
Samim

**Comment by al1b** [comment]
Are you talking about Linux file system permissions?

**Comment by psamim** [comment]
Yes, the file has executable permission. Maybe it is a dotnet issue.

**Comment by al1b** [comment]
This issue is a `dotnet` issue on Linux. 

https://github.com/dotnet/coreclr/pull/7995
https://docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6
