### ISSUE TITLE
Bad log file name

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#4]
Hi,

The log file name starts with two dashes (e.g. `--persianerrors`), it makes working with them extremely difficult or impossible in Linux shells. Because the shell arguments also start with two dashes, so the shell is confused.

Example:
```txt
$ cat '--perisanerrors.txt'

cat: unrecognized option '--perisanerrors.txt'
Try 'cat --help' for more information.
```

or 

```txt
 $ cp "--perisanerrors.txt" .

cp: unrecognized option '--perisanerrors.txt'
Try 'cp --help' for more information.
```

**Comment by al1b** [comment]
The log file names should not start with two dashes. As you have already resolved it here (https://github.com/al1b/KTOP/issues/2) it's a bug related to command line parser.

**Comment by al1b** [comment]
@psamim 
The log file names should not start with two dashes. As you have already resolved it here (https://github.com/al1b/KTOP/issues/2) it's a bug related to command line parser.

**Comment by al1b** [comment]
@psamim 

Fixed.

**Comment by psamim** [comment]
Thanks! It is fine now. :)
