### ISSUE TITLE
azw3 support

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#5]
Hi,

in https://github.com/al1b/KTOP/blob/master/src/KTOP.Base/BookEngine.cs#L50, it seems that no other file than epub is supported. Can we have azw3 support for Kindles? Or should I convert the output epub to azw3 using Calibre?

**Comment by al1b** [comment]
KTOP doesn't support azw3 and mobi yet, but it is in its roadmap.

> Or should I convert the output epub to azw3 using Calibre?

For now, yes.

**Comment by al1b** [comment]
The project is deprecated now. Please use Calibre plugin , KiPEO instead:
https://github.com/al1b/Calibre-KiPEO
