### ISSUE TITLE
AUR Package Build Error

### ISSUE THREAD

**Issue by psamim** [al1b/KTOP#8]
Hi,

This below commit caused AUR builds to fail, as it only comments out the `win7-x64` runtime.

https://github.com/al1b/KTOP/commit/39ce29543727d524582f548cda740d5d5718f79b#diff-f130677e38d69533e908c907b5435bb7L7

Thanks,
Samim

**Comment by al1b** [comment]
@psamim 
That was a wrong commit. Thanks

**Comment by psamim** [comment]
@al1b Thanks
