### ISSUE TITLE
adam

### ISSUE THREAD

**Issue by hamedart** [al1b/KTOP#9]
[آدم آدم است.pdf](https://github.com/al1b/KTOP/files/663217/default.pdf)
##

**Comment by al1b** [comment]
What's this ebook?

**Comment by al1b** [comment]
Since you haven't provided any information I have to close this issue. As we know KTOP only supports `epub` ebooks. If you wanted to have better experience of reading `pdf` ebooks I suggest you to take a look on [K2pdfopt](www.willus.com/k2pdfopt/) project. You can reflow your books with it.
